version: '3.8'  # تحديد إصدار Docker Compose

services:  # تعريف الخدمات المختلفة
  api:  # الخدمة الخاصة بالواجهة الخلفية
    build: ./backend  # مسار بناء الصورة
    environment:  # المتغيرات البيئية
      - JWT_SECRET=please-change-me  # سر JWT
      - APP_DIR=/app  # مسار التطبيق
      - DATABASE_URL=sqlite:////app/db.sqlite3  # عنوان قاعدة البيانات
    volumes:  # تحديد المجلدات المشتركة
      - api_data:/app  # ربط مجلد البيانات
    ports:  # تحديد المنافذ
      - "8000:8000"  # ربط المنفذ 8000 في الحاوية مع المنفذ 8000 في المضيف

  frontend:  # الخدمة الخاصة بالواجهة الأمامية
    image: nginx:alpine  # استخدام صورة Nginx خفيفة
    volumes:  # تحديد المجلدات المشتركة
      - ./frontend:/usr/share/nginx/html:ro  # ربط مجلد الواجهة الأمامية
    ports:  # تحديد المنافذ
      - "8080:80"  # ربط المنفذ 80 في الحاوية مع المنفذ 8080 في المضيف
    depends_on:  # تحديد الاعتمادات
      - api  # تعتمد الواجهة الأمامية على خدمة الواجهة الخلفية

volumes:  # تعريف الأحجام
  api_data:  # حجم لتخزين بيانات الواجهة الخلفية
name: CI

on:
  push:
    branches: [ "**" ]  # تنفيذ CI لكل الفروع
  pull_request:  # تنفيذ CI عند تقديم طلب سحب

jobs:                                  
  build:                                
    runs-on: ubuntu-latest  # تشغيل الوظيفة على أحدث إصدار من Ubuntu

    steps:                                
      - name: Checkout code
        uses: actions/checkout@v4  # جلب الشيفرة المصدرية من المستودع

      - name: Set up Python
        uses: actions/setup-python@v5  # إعداد بيئة Python
        with:                                
          python-version: '3.11'  # تحديد إصدار Python

      - name: Install backend dependencies
        run: |  # تثبيت التبعيات مباشرة
          python -m pip install --upgrade pip  # تحديث pip
          pip install fastapi pandas scikit-learn  # تثبيت الحزم المطلوبة مباشرة

      - name: Import check
        run: python -c "import fastapi, pandas, sklearn; print('Imports OK')"  # التحقق من استيراد المكتبات

      - name: Install Docker Compose
        run: |  # تثبيت Docker Compose
          sudo apt-get update  # تحديث قائمة الحزم
          sudo apt-get install -y docker-compose  # تثبيت Docker Compose

      - name: Build Docker images
        run: docker-compose build  # بناء صور Docker
